import urllib.request
import urllib.parse
import json
import sys

SUPABASE_URL = 'https://dmqzixpappullrnyospj.supabase.co'
KEY = 'sb_publishable_UcusGk4UNMVEp82y_2jSdA_dQGjd1bH'
HEADERS = {
    'apikey': KEY,
    'Authorization': f'Bearer {KEY}',
    'Content-Type': 'application/json',
    'Prefer': 'return=representation'
}

def supabase_get(path):
    req = urllib.request.Request(f'{SUPABASE_URL}/rest/v1/{path}', headers=HEADERS)
    with urllib.request.urlopen(req) as r:
        return json.loads(r.read())

def supabase_post(path, data, prefer='return=representation'):
    h = {**HEADERS, 'Prefer': prefer}
    body = json.dumps(data).encode('utf-8')
    req = urllib.request.Request(f'{SUPABASE_URL}/rest/v1/{path}', data=body, headers=h, method='POST')
    try:
        with urllib.request.urlopen(req) as r:
            body = r.read()
            return json.loads(body) if body.strip() else True
    except urllib.error.HTTPError as e:
        print(f'  ERROR {e.code}: {e.read().decode()}')
        return None

# ── 1. 카테고리 생성 ─────────────────────────────────────────────
CATS = [
    ('영상진단장비',    '영상진단장비'),
    ('내시경장비',      '내시경장비'),
    ('검사측정장비',    '검사/측정장비'),
    ('물리치료재활장비','물리치료/재활장비'),
    ('치료장비',        '치료장비'),
    ('병상침대류',      '병상/침대류'),
    ('멸균소독장비',    '멸균/소독장비'),
    ('기타의료기기',    '기타의료기기'),
    ('환자모니터링장비','환자모니터링장비'),
    ('수술장비',        '수술장비'),
    ('수술기구소모품',  '수술기구/소모품'),
    ('수술실병원가구',  '수술실/병원가구'),
    ('온열냉각기기',    '온열/냉각기기'),
]

CAT_ID_MAP = {
    '영상진단장비':     '영상진단장비',
    '내시경장비':       '내시경장비',
    '검사/측정장비':    '검사측정장비',
    '물리치료/재활장비':'물리치료재활장비',
    '치료장비':         '치료장비',
    '병상/침대류':      '병상침대류',
    '멸균/소독장비':    '멸균소독장비',
    '기타의료기기':     '기타의료기기',
    '환자모니터링장비': '환자모니터링장비',
    '수술장비':         '수술장비',
    '수술기구/소모품':  '수술기구소모품',
    '수술실/병원가구':  '수술실병원가구',
    '온열/냉각기기':    '온열냉각기기',
}

print('=== 카테고리 등록 ===')
existing_cats = supabase_get('categories?select=cat_id')
existing_cat_ids = {c['cat_id'] for c in existing_cats}

for cat_id, name in CATS:
    if cat_id in existing_cat_ids:
        print(f'  [SKIP] {name} ({cat_id}) - 이미 존재')
    else:
        result = supabase_post('categories', {
            'cat_id': cat_id, 'name': name, 'color_key': 'blue', 'sort_order': 0
        })
        print(f'  [OK]   {name} ({cat_id}) 생성완료')

# ── 2. 기존 모델명 조회 ──────────────────────────────────────────
print('\n=== 기존 장비 조회 ===')
existing_equip = supabase_get('equipment?select=model_name&limit=1000')
existing_models = {(e['model_name'] or '').lower() for e in existing_equip}
print(f'  기존 장비 {len(existing_models)}개 조회 완료')

# ── 3. 장비 데이터 ────────────────────────────────────────────────
RAW = [
    ('영상진단장비','X-Ray','XVISION-525R','GEMSS Healthcare'),
    ('내시경장비','Endoscope','OLYMPUS-CV290','OLYMPUS'),
    ('영상진단장비','DR','BSD -4343','BONTECH'),
    ('영상진단장비','DR','RFA-1717','DRGEM'),
    ('영상진단장비','DR','FV4343','FUTURAYTEC'),
    ('영상진단장비','초음파진단기','LOGIGQ-F','GE HealthCare'),
    ('물리치료/재활장비','ESWT','Piezo+Radial','weverinstruments'),
    ('물리치료/재활장비','자기장치료기','TESLA-3000','weverinstruments'),
    ('영상진단장비','ICT 간섭파치료기','Lectron-350RI','DMC'),
    ('치료장비','고주파치료기','HIPER-500','JS-ON'),
    ('영상진단장비','Mammography','PINKVIEW-BT','BEMEMS'),
    ('영상진단장비','DR','ACQUIDR-Mano4343T','LG'),
    ('치료장비','LASER','Ulthera','Merz Aesthetics'),
    ('물리치료/재활장비','ESWT','Piezo+Airgun+HILT','weverinstruments'),
    ('내시경장비','Endoscope','Olympus-CV260','OLYMPUS'),
    ('물리치료/재활장비','ESWT','Ulforce','ITC'),
    ('영상진단장비','Mammography','PINKVIEW-DR Prime','BEMEMS'),
    ('병상/침대류','Hospital Bed','YN-702A','영남베드'),
    ('물리치료/재활장비','ESWT','DUALWAVE','MEDIZEN'),
    ('영상진단장비','Traction','Wintrac,LC-100','메이저메디칼'),
    ('영상진단장비','Mammography','PINKVIEW-SMART','BEMEMS'),
    ('멸균/소독장비','Steam Sterilizer','48L-HL480S','HONGIK MEDICAL SYSTEMS'),
    ('영상진단장비','X-Ray','APEX','신영'),
    ('기타의료기기','CR','FCR PRIMA TM','SHINKI'),
    ('치료장비','질이완증치료기','EVERO','SNJ'),
    ('내시경장비','Endoscope','EUXEO 700SERIES','EVE MEDICAL'),
    ('영상진단장비','Bucky Stand','SMS-BS-2','GEMSS Healthcare'),
    ('병상/침대류','GYN Exam Table','JS-005-1','Jinsol Medical'),
    ('환자모니터링장비','자동혈압계','BPbio320','Inbody'),
    ('물리치료/재활장비','ESWT','Piezo+HILT','weverinstruments'),
    ('멸균/소독장비','Steam Sterilizer','ST-50R','SUNWOOTECH'),
    ('물리치료/재활장비','ESWT','Shock Wave F1','WMEDIX'),
    ('환자모니터링장비','EKG','CARDIPIA 800H','TRISMED'),
    ('치료장비','Infrared Lamp','IR-VITA','Goodpl'),
    ('영상진단장비','DR','1417WCE','Rayence'),
    ('병상/침대류','Examining Table','BS-105,평침','장미'),
    ('기타의료기기','근육타진기','01M7,일반형','01M'),
    ('환자모니터링장비','Patient Monitor','BT-740','bistos'),
    ('물리치료/재활장비','MicroWave','DT-02','DMC'),
    ('내시경장비','내시경소독기','ENDO Clean-1000','MEDPIA'),
    ('영상진단장비','Bucky Stand','','GEMSS Healthcare'),
    ('기타의료기기','초음파치료기','Shurink','CLASSYS'),
    ('기타의료기기','동맥경화진단기','VP-1000Plus','동아에스티'),
    ('기타의료기기','초음진단기','HS40','SAMSUNG MEDISON'),
    ('물리치료/재활장비','CPM','Artus-903K','EUGENE'),
    ('수술장비','Operating Light','Luvis S100','Dentis'),
    ('기타의료기기','Tread Mill','Case&T2100','GE HealthCare'),
    ('영상진단장비','ICT','PMI-3000','Stratek'),
    ('물리치료/재활장비','Therapy Laser','Red Laser/DR-12','DMC'),
    ('기타의료기기','Cryo','FROZEN C','MESH'),
    ('영상진단장비','ICT','','인성테크놀로지'),
    ('영상진단장비','Chiropractic','CM500','카이로메디'),
    ('물리치료/재활장비','CPM','Artus-701ES','EUGENE'),
    ('멸균/소독장비','Steam Sterilizer','MK50L (MK-N50V)','MKT'),
    ('기타의료기기','Visual System','XV3 mini','동아참메드'),
    ('기타의료기기','Spirometer','AVAD9','MEDIREN'),
    ('검사/측정장비','Bondensitometer','DR PLUS','BEMEMS'),
    ('수술장비','Operating Table','JS-003-1','Jinsol Medical'),
    ('기타의료기기','질타이트닝','HERA V','ELIMTEK'),
    ('영상진단장비','DR','BT-DB24-IA / CSI+IMFOU','iRay'),
    ('기타의료기기','Spain blance','MS-3000','지엠텍'),
    ('기타의료기기','Anesthesia Machine','MULTIPLUS','ROYALMED'),
    ('기타의료기기','VNG','SLVNG','SLMED'),
    ('기타의료기기','LDM','LDM SMART TRI','WELLCOMET'),
    ('기타의료기기','적외선체열진단기','InnerVue3-K','Medicore'),
    ('기타의료기기','EMG','NATUSS100','HiMed'),
    ('영상진단장비','DR','EXPD 4357','디알텍'),
    ('기타의료기기','ENT-Unit','XU1 extreme','참메드'),
    ('환자모니터링장비','Pulse Oxymeter','Oxyren9','메디렌'),
    ('병상/침대류','전동테이블','E100','hck'),
    ('수술장비','Operating Light','Luvis','Dentis'),
    ('기타의료기기','질세정기','APRO-110','Apro Korea'),
    ('병상/침대류','Leander Table','IWS-7000','Iwellness'),
    ('치료장비','IPL (Cellec V)','SmoothCool','Jeisys'),
    ('치료장비','Nd-Yag Laser','루카스','amt'),
    ('영상진단장비','X-Ray','REX525R','Listem'),
    ('영상진단장비','DR','Rayence 1417WCC','Rayence'),
    ('병상/침대류','Leander Table','IWS-7000A','아이웰리스'),
    ('내시경장비','Endoscope','CV260','OLYMPUS'),
    ('병상/침대류','Stretcher Car','DSM-101','Dae Sang medical'),
    ('기타의료기기','Ion Cooler','E&FM 100','오릭스'),
    ('수술기구/소모품','Needle Tens','STN-330','Stratek'),
    ('영상진단장비','ICT','D&B','Gooldpl'),
    ('기타의료기기','Sling','제로비티 슬링 3단','01M'),
    ('기타의료기기','Zerovity Therapy Sling 3way','R9-4','01M'),
    ('기타의료기기','고압산소치료기','O2 one H-810','Mediconet'),
    ('기타의료기기','Exbody System','9100','Exbody'),
    ('병상/침대류','GYN Exam Table','JS-005','Jinsol Medical'),
    ('수술장비','Operating Light','JS-1000/Dual-LED','Jinsol Medical'),
    ('영상진단장비','ICT','KM-2900JT','Medi Round'),
    ('병상/침대류','Examining Table','DSM-2241','Dae Sang medical'),
    ('검사/측정장비','체성분분석기','INBODY-270','Inbody'),
    ('기타의료기기','FES','Microstim2','Sejin MT'),
    ('영상진단장비','X-Ray','AccuRay-D5','DK Medical (동강)'),
    ('병상/침대류','전동테이블','CTT-202','펄시'),
    ('병상/침대류','Stretcher Car','YHS-201','Kareroom'),
    ('내시경장비','Endoscope','EPK-i7000','Pentax'),
    ('검사/측정장비','체성분분석기','Mediana, i20','Mediana'),
    ('멸균/소독장비','Steam Sterilizer','VSC-250L','Person Medical'),
    ('기타의료기기','Insight','','인사이트'),
    ('기타의료기기','카이로프랙틱','CWM-300','Chiro medi'),
    ('기타의료기기','약탕추출기','ks220','Kyungseo E&P'),
    ('영상진단장비','DR','BT-DB22W / GADOX+JPI','Bon Tech'),
    ('병상/침대류','Hospital Bed','YN-701A','Kareroom'),
    ('영상진단장비','C-Arm Table','KF-906','펄시'),
    ('기타의료기기','Ergometer Bycle','SE-1000','성진엠티'),
    ('물리치료/재활장비','ESWT','Piezo-Di2','DMC'),
    ('내시경장비','내시경 CO2 자동주입기','VS-300CF','Vision Medical'),
    ('병상/침대류','전동테이블','M4-3','01M'),
    ('수술장비','고주파수술기','ST-501','썸텍'),
    ('영상진단장비','DR','BT-DB24-IA / CSI+JPI','디알텍'),
    ('수술장비','Operating Table','JS-002','Jinsol Medical'),
    ('기타의료기기','바이오피드백','HnJ-7000','Furun Medical'),
    ('영상진단장비','X-Ray','SIG-40-525','에코레이'),
    ('검사/측정장비','당화혈색소','Afinion 2','그린메디칼'),
    ('병상/침대류','Examining Table','열선','장미'),
    ('환자모니터링장비','Defibrillator','AED,A15','씨유'),
    ('영상진단장비','X-Ray Fixed Table','','대경메디칼'),
    ('기타의료기기','ENT-Chair','YS-3000','제이알메디'),
    ('기타의료기기','동맥경화진단기','omron-VP1000plus','Omron'),
    ('기타의료기기','UDS Alpha','요속측정기','지앤씨앤티'),
    ('기타의료기기','올리지오','oligio','원텍'),
    ('영상진단장비','DR','PIXX 1717','픽젠'),
    ('기타의료기기','Nebulizer','XCN5 extreme','참메드'),
    ('병상/침대류','전동테이블','CT-102','펄시'),
    ('영상진단장비','ICT','BioTron-DX','디엠씨'),
    ('영상진단장비','Chiropractic','Raphael 606','영일엠'),
    ('영상진단장비','DR','BT-DB24-IA / GADOX+GODR','본테크'),
    ('멸균/소독장비','Steam Sterilizer','ST-30R','선우테크놀로지'),
    ('기타의료기기','PACS','','후지'),
    ('검사/측정장비','당화혈색소','Afinion / HbA1C','그린메디칼'),
    ('병상/침대류','전동테이블','M4-2','영일엠'),
    ('검사/측정장비','자동신장체중계','GL-150R','G tech'),
    ('기타의료기기','약포장기','세이버I / KH15200','경서기계'),
    ('기타의료기기','ENT-Unit','Grand-2000S','Med Star'),
    ('기타의료기기','EMG','Sierra Wave','영우메디텍'),
    ('기타의료기기','Visual System','SuperVision HD','Med Star'),
    ('환자모니터링장비','Pulse Oxymeter','BT-710','bistos'),
    ('수술장비','Bovie','Zeus-150','01'),
    ('수술장비','Operating Table','JS-001','Jinsol Medical'),
    ('기타의료기기','CR','fcr capsula XLII','신기사'),
    ('내시경장비','내시경캐비넷','PS-04 (Model Endojang)','Apex Korea'),
    ('치료장비','CO2 Laser','DS','DSE'),
    ('기타의료기기','초음파자극기','GP-200','Gooldpl'),
    ('수술장비','Operating Light','JS-009(L)/5+6LED','Jinsol Medical'),
    ('기타의료기기','핫팩커버','','삼부메디칼'),
    ('기타의료기기','Spine Balance','BT-3000A','지엠텍'),
    ('멸균/소독장비','Steam Sterilizer','MCL-50V','Medi Ster'),
    ('치료장비','CO2 Laser','DS-40U','DSE'),
    ('기타의료기기','Smartro Wave','CWM-703','Chungwoo Medical'),
    ('병상/침대류','전동테이블','go-2000','Neo Tech'),
    ('물리치료/재활장비','ESWT','E-Therapy','Gooldpl'),
    ('기타의료기기','옴니핏','OMNIFIT mind care','Omnifit'),
    ('영상진단장비','AI X-Ray','Remex KA6','Remedi'),
    ('기타의료기기','Techheim PACS','ViewRex3','Tech Heim'),
    ('병상/침대류','전동테이블','E102','hck'),
    ('영상진단장비','Suction','JS-007','Jinsol Medical'),
    ('기타의료기기','전침','GP-304N','Gooldpl'),
    ('환자모니터링장비','자동혈압계','ACCUNIQ, BP800','셀바스코리아'),
    ('기타의료기기','방사선저감장치','CVP-2','신기사'),
    ('기타의료기기','환자복','','금성메디가운'),
    ('병상/침대류','전동테이블','M2-1','01M'),
    ('멸균/소독장비','Steam Sterilizer','VSC-92L','퍼슨메디칼'),
    ('수술장비','Operating Table','JS-002S','진솔의료기'),
    ('병상/침대류','Examining Table','YB-E1002','영남베드'),
    ('병상/침대류','Tilting Table','GO-9000','네오텍'),
    ('기타의료기기','황토베드','1800x700mm','신화'),
    ('기타의료기기','Dental Chair','','한림덴텍'),
    ('기타의료기기','메조프래쉬','Q-jet','웰니스플렛폼'),
    ('영상진단장비','Traction','','디엠씨'),
    ('검사/측정장비','자동신장체중계','BSM-330','인바디'),
    ('검사/측정장비','잔뇨측정기','BioCon-900','엠큐브'),
    ('기타의료기기','황토베드','','신화'),
    ('영상진단장비','Traction','AT-5,2인용','디엠씨'),
    ('멸균/소독장비','E.O. Gas 소독기','MK-EO50','엠케이티'),
    ('병상/침대류','Examining Table','','장미'),
    ('병상/침대류','전동테이블','M2-7','영일엠'),
    ('영상진단장비','X-Ray','','신영'),
    ('기타의료기기','Tourniquet','TOURNI-3000','퍼슨메디칼'),
    ('환자모니터링장비','EKG','Cardio7','바이오넷'),
    ('환자모니터링장비','Patient Monitor','M50S','메디아나'),
    ('병상/침대류','Stretcher Car','YB-W1002','영남베드'),
    ('기타의료기기','Syringe Pump','DS-3000','대회기기'),
    ('기타의료기기','A/S Charge','',''),
    ('멸균/소독장비','Plazma Sterilizer','MK-PL50','엠케이티'),
    ('병상/침대류','Stretcher Car','S2-1,유압1단','영일엠'),
    ('수술장비','Operating Light','Elpis','엘피스코리아'),
    ('병상/침대류','4-Way table','','잼스헬스케어'),
    ('검사/측정장비','당화혈색소','Afinion2','그린바이이메디칼'),
    ('영상진단장비','Chiropractic','Raphael 404','영일엠'),
    ('병상/침대류','전동침대','YN-733A','영남베드'),
    ('기타의료기기','Bobath Table','GO-5700','네오텍'),
    ('멸균/소독장비','Steam Sterilizer','MK-25NS','엠케이티'),
    ('수술실/병원가구','Sheet Cover','','금성까운'),
    ('병상/침대류','Stretcher Car','S2-2,유압2단','영일엠'),
    ('병상/침대류','Hospital Bed','','영남베드'),
    ('영상진단장비','Bucky Stand','ECO-BS-3','에코레이'),
    ('수술실/병원가구','Standing Table','SO-1000','네오텍'),
    ('병상/침대류','Hospital Bed','2-Crank','삼기침대'),
    ('온열/냉각기기','Hot-Pack','냉온찜질 Cool & Hot Pack','아성'),
    ('영상진단장비','초음파진단기','bionet,H10L Linear','바이오넷'),
    ('온열/냉각기기','Hot-Pack','전기핫백','아성'),
    ('영상진단장비','Disposable Polypectomy Snare','','멘피스코리아'),
    ('환자모니터링장비','자동혈압계','ACCUNIQ, BP500P','셀바스코리아'),
    ('환자모니터링장비','Defibrillator','HR-501','메디코아'),
    ('병상/침대류','전동테이블','M3-4','영일엠'),
    ('수술장비','고주파수술기','Dr.Oppel ST-501','썸텍'),
    ('멸균/소독장비','Plazma Sterilizer','MK-PL35','엠케이티'),
    ('수술장비','Bovie','','아이티시'),
    ('검사/측정장비','Urine Analyzer','Urometer-120','디에프아이'),
    ('온열/냉각기기','Hot-Pack Unit','GP-24PN','굿플'),
    ('기타의료기기','Iontophoresis','TAE-2002','오릭스'),
    ('기타의료기기','Operating Microscope','','칼자이스'),
    ('기타의료기기','질세정기 실리콘팁','50s/pack','아프코리아'),
    ('수술장비','Operating Table','JS-003','진솔의료기'),
    ('기타의료기기','CO2 주입기','VS-300C','비전과학'),
    ('기타의료기기','Redcord Rehab Pro 레드코드','TESMA','그린모아텍'),
    ('수술실/병원가구','Shower Cart','YST-301','영남베드'),
    ('물리치료/재활장비','저주파자극기','GP-400P','굿플'),
    ('영상진단장비','Fractional Laser','Mutixell','대신엔터프라이즈'),
    ('기타의료기기','Anesthesia Machine','ROYAL-77','로얄메디칼'),
    ('기타의료기기','타임호출기','D-8000','도도텍'),
    ('영상진단장비','X-Ray 콘덴서','GXR-C40S','디알젬'),
    ('온열/냉각기기','Hot-Pack Cover','','삼보메디칼'),
    ('온열/냉각기기','Hot-Pack Unit','GP-24PD','굿플'),
    ('병상/침대류','Examining Table','','엠케이베드'),
    ('기타의료기기','Gate Way','HD','게이트'),
    ('기타의료기기','Scrub Station','1인용','케이엔티'),
    ('병상/침대류','전동테이블','CT-100','펄시'),
    ('기타의료기기','Side Lamp','JS-013-1','진솔의료기'),
    ('병상/침대류','Patient Stool','AS-300','엠코니'),
    ('환자모니터링장비','Patient Monitor','M40','메디아나'),
    ('물리치료/재활장비','저주파자극기','GP-400D','굿플'),
    ('기타의료기기','홀터모니터 운동부하','TANGO M2','비티엘'),
    ('물리치료/재활장비','ESWT 체외충격파','DUAL ACTIVE F','케이원메드'),
    ('기타의료기기','시력표','Acryl,성인용','한천석'),
    ('기타의료기기','이불 (면40수)','','칠성이불'),
    ('온열/냉각기기','Hot-Pack Unit','12Pack','아성'),
    ('기타의료기기','Wheel Chair','MAX-1012','메디타운'),
    ('내시경장비','Endoscope Monitor','','엘지'),
    ('기타의료기기','Mobile Utility','Y101A','열린세상'),
    ('치료장비','냉각치료기','Cryo-master','매쉬'),
    ('병상/침대류','전동테이블','TTM-B','팜파스'),
    ('병상/침대류','Hospital Bed','1-Motor','영남베드'),
    ('기타의료기기','납 Glove','Lead Glove','성광메디텍'),
    ('수술장비','Bovie','ITC250D','아이티시'),
    ('기타의료기기','Wheel Chair Scale','GWS-200','지테크'),
    ('기타의료기기','이전설치료 Charge','','와이비메디칼'),
    ('영상진단장비','ICT','CWM-103D','청우메디칼'),
    ('멸균/소독장비','Steam Sterilizer','HS-3041SD','한신메디칼'),
    ('물리치료/재활장비','상하지운동기','SOP-1100','성도엠씨'),
    ('병상/침대류','Stretcher Car','N300','네오텍'),
    ('물리치료/재활장비','MicroWave','','인성테크놀로지'),
    ('기타의료기기','Infusion Pump','DI-2000','대회기계'),
    ('기타의료기기','Nebulizer','NW-3000','메드스타'),
    ('환자모니터링장비','Patient Monitor','BT-770','비스토스'),
    ('기타의료기기','Vaginal Speculum','Small','바다르산스'),
    ('기타의료기기','산소발생기','Aeroplus5','조인메디칼'),
    ('병상/침대류','전동테이블','M2-4','영일엠'),
    ('기타의료기기','TDP 신등','CQ-31','대원'),
    ('기타의료기기','Aqua Peel','AGE System','GE HealthCare'),
    ('기타의료기기','설치료 Charge','','와이비메디칼'),
    ('병상/침대류','Stretcher Car','YHS-201C','삼기침대'),
    ('병상/침대류','Stretcher Car','N-300','에이치씨케이'),
    ('물리치료/재활장비','MicroWave','SCAN LASER','굿플'),
    ('영상진단장비','초음파진단기','JUNIFER','지멘스'),
    ('기타의료기기','Ultrasound','P9','지이헬스케어'),
    ('멸균/소독장비','Steam Sterilizer','ST-60R','선우테크놀러지'),
    ('기타의료기기','Multi Ion Cool','IONCOOL','케이원메드'),
    ('병상/침대류','Examining Table','A1-JT103','장미'),
    ('기타의료기기','E.O. Gas','Person-EO50L','퍼슨메디칼'),
    ('기타의료기기','E.O. Gas','MK-EO50','엠케이티'),
    ('기타의료기기','Auto Tens','GP-400P','굿플'),
    ('영상진단장비','ICT','GP-512D','굿플'),
    ('기타의료기기','천정레일형 보행훈련기','TM TYPE2','그린모아텍'),
    ('병상/침대류','Examining Table','YB-E1001','영남베드'),
    ('물리치료/재활장비','상하지운동기','MC-1','성도엠씨'),
    ('영상진단장비','Traction','SST-300','스트라텍'),
    ('영상진단장비','X-Ray','Portable REMEX-T100','레이케어'),
    ('기타의료기기','E.O. Gas Stemsterlizer','MK-EO30','엠케이티'),
    ('치료장비','CO2 Laser','Multixel DS-40Ub','대신엔터프라이즈'),
    ('기타의료기기','Anoscope','Dr.Camscope','조인메디칼'),
    ('검사/측정장비','자동신장체중계','DS-B03','동산제닉스'),
    ('기타의료기기','Uroflowmeters','MMS','지앤씨앤티'),
    ('기타의료기기','T/F Rolls 운동용롤','3개세트','네오텍'),
    ('병상/침대류','Stretcher Car','DW-3001','hck'),
    ('병상/침대류','전동테이블','M2-3','영일엠'),
    ('수술실/병원가구','IV Pole','링겔대,5발바퀴함장착형','지엠텍'),
    ('물리치료/재활장비','수치료기','냉각기','씨어테크놀로지'),
    ('병상/침대류','전동테이블','D','영일엠'),
    ('기타의료기기','공기압치료기','보급형','닥터라이프'),
    ('환자모니터링장비','자동혈압계','BP-600','셀바스코리아'),
    ('수술장비','Bovie','Zeus-400','제로원'),
    ('수술장비','Operating Table','OT-500S','서광메딕스'),
    ('기타의료기기','Ultrasound','LECTRON-200UD','디엠씨'),
    ('치료장비','의료용레이저','AP2165','앞썬아이앤씨'),
    ('기타의료기기','Microscope 모세혈관현미경','DBM-1600','동원과학'),
    ('기타의료기기','Disposable Hemoclip','','멤피스코리아'),
    ('영상진단장비','Disposable Injection Needle','','멤피스코리아'),
    ('검사/측정장비','Urine Analyzer','CR-50','디에프아이'),
    ('병상/침대류','Examining Table','Siderail','엠케이베드'),
    ('물리치료/재활장비','상하지운동기','SP-1100','성도엠씨'),
    ('검사/측정장비','체성분분석기','Mediana, i30','메디아나'),
    ('멸균/소독장비','Steam Sterilizer','HS-3035SD','한신메디칼'),
    ('멸균/소독장비','Steam Sterilizer','SC-48S','퍼슨메디칼'),
    ('영상진단장비','X-Ray 콘덴서','','신영'),
    ('수술장비','Operating Light','JS-201','진솔의료기'),
    ('기타의료기기','High PACS','','후지'),
    ('기타의료기기','Blood Cell Counter','','마인드레이'),
    ('병상/침대류','전동테이블','gr-4000','베스트웍'),
    ('기타의료기기','Auto Tourniquet','TOURNI-2000','퍼슨메디칼'),
    ('기타의료기기','Wedge','2개세트','GE HealthCare'),
    ('기타의료기기','Classic Wood Reformer','CWR 3000','아성'),
    ('기타의료기기','Skin Scrubber','Ionto-Son','케이원메드'),
    ('기타의료기기','Bobath Table','주문제작','네오텍'),
    ('기타의료기기','O2 Gage','KB-100','고봉통상'),
    ('영상진단장비','Dressing Forceps','','바다르산스'),
    ('검사/측정장비','당화혈색소','Afinion AS100','그린메디칼'),
    ('영상진단장비','MFT - Manual Function Test','',''),
    ('기타의료기기','Fetal Monitor','BT-350LCD','비스토스'),
    ('기타의료기기','전기핫팩','','대신전자'),
    ('검사/측정장비','자동신장체중계','BSM-270','인바디'),
    ('환자모니터링장비','무수은혈압계 BPbio220','Bpbio-220','인바디'),
    ('병상/침대류','Examining Table','주문제작','엠케이베드'),
    ('멸균/소독장비','U-V Sterilizer','KRS-600T-25L','카리스'),
    ('영상진단장비','Dressing Forceps','25cm','장우양행'),
    ('수술실/병원가구','IV Pole','링겔대,5발바퀴(프라스틱)','지엠텍'),
    ('병상/침대류','Stretcher Car','S1-1,기본형','영일엠'),
    ('기타의료기기','Orthopedic Table','JS-015','진솔의료기'),
    ('검사/측정장비','Hematology Analyzer','DH-26','메디스타'),
    ('환자모니터링장비','EKG','Cardio7_S','바이오넷'),
    ('치료장비','냉각치료기','CRYO','메디젠'),
    ('물리치료/재활장비','Therapy Laser','DUO LIGHT','케이원메드'),
    ('치료장비','Infrared Lamp','XCS5 extreme','메드스타'),
    ('기타의료기기','Screen','3-Panels','지엠텍'),
    ('병상/침대류','Tilting Table','R3-2','영일엠'),
    ('수술장비','Operating Light','JS-011/5L','진솔의료기'),
    ('기타의료기기','납파티션','방호칸막이','디알뷰'),
    ('환자모니터링장비','자동혈압계','ACCUNIQ, BP500','셀바스코리아'),
    ('병상/침대류','전동테이블','','펄시'),
    ('온열/냉각기기','Hot-Pack Unit','KRS-24PA','카리스'),
    ('기타의료기기','공기압치료기','MK-10','대상헬스케어'),
    ('영상진단장비','Dressing Car','서랍2식','지엠텍'),
    ('영상진단장비','Traction','AT-5,1인용','디엠씨'),
    ('병상/침대류','Tilting Table','E402','네오텍'),
    ('기타의료기기','Ultrasound','DS-SONO1001','오릭스'),
    ('기타의료기기','LED Therapy','OMEGA Light','비올'),
    ('병상/침대류','전동테이블','PAMB-740','팜파스'),
    ('기타의료기기','EMT PACS Server','','테크하임'),
    ('기타의료기기','면역분석기','AFIAS-6','그린바이오메디칼'),
    ('기타의료기기','작업테이블','E800','네오텍'),
    ('기타의료기기','Wilson Frame','체스트바','진솔의료기'),
    ('수술장비','Operating Light','JS-010/7L','진솔의료기'),
    ('영상진단장비','AI X-Ray','','오톰'),
    ('병상/침대류','Leander Table','','영일엠'),
    ('수술실/병원가구','Bedside Cabinet','주문제작','영남베드'),
    ('기타의료기기','EKG Accessory','Cart','제로원'),
    ('기타의료기기','O2 Tank','10kg','대성가스'),
    ('기타의료기기','O2 Flowmeter','','고봉통상'),
    ('기타의료기기','Zerovity Therapy Sling SET','R7-1','모아텍'),
    ('기타의료기기','Air Compressor','','메디피아'),
    ('수술장비','Bovie','ITC150P','아이티시'),
    ('기타의료기기','Ambu Bag','Adult','대석양행'),
    ('병상/침대류','Hospital Bed','1-Crank','영남베드'),
    ('병상/침대류','Stretcher Car','HL-SK310','hck'),
    ('기타의료기기','Cast Cutter','HCC-114','한신메디칼'),
    ('기타의료기기','연하장애전기자극치료기','STF-3300','세진엠티'),
    ('기타의료기기','Ultrasound','AT-1100','휴먼스캔'),
    ('기타의료기기','PC Set','',''),
    ('병상/침대류','전동테이블','온열매트','장미'),
    ('기타의료기기','Redcord Narrow Sling 레드코드 네로우슬링','','모아텍'),
    ('기타의료기기','Audiometer','DB23000','대합성'),
    ('물리치료/재활장비','Therapy Laser','Chungwoo','청우메디칼'),
    ('영상진단장비','Smoke Suction','SSB Eva','제이비에스인터내셔널'),
    ('수술장비','Operating Light','JS-011(L)/5LED','진솔의료기'),
    ('물리치료/재활장비','Therapy Laser','STL-101','스트라텍'),
    ('기타의료기기','Ultrasound','GP-200','굿플'),
    ('기타의료기기','PACS Server','','후지'),
    ('환자모니터링장비','Patient Monitor','M30','메디아나'),
    ('기타의료기기','시력표','Acryl,Slim성인용','한천석'),
    ('기타의료기기','Biopsy Punch Forcep','','솔고의료기'),
    ('환자모니터링장비','무수은혈압계','','인바디'),
    ('기타의료기기','Personal Computer','',''),
    ('물리치료/재활장비','ESWT','','영인바이오텍'),
    ('기타의료기기','Vaginal Speculum','Medium','장우양행'),
    ('기타의료기기','저주파치료기','','굿플'),
    ('기타의료기기','피부 냉동치료기','Cryoderm',''),
    ('기타의료기기','전동체어','3단체어','hck'),
    ('치료장비','고주파치료기','MAGICPOT','윈백'),
    ('기타의료기기','초음파치료기','ST-10A','스트라텍'),
    ('멸균/소독장비','Plazma Sterilizer','',''),
    ('수술기구/소모품','Disposable Biopsy Forceps','','멤피스코리아'),
    ('병상/침대류','Stretcher Car','MB-3001','삼기침대'),
    ('병상/침대류','전동테이블','Foot Switch','베스트웍스'),
    ('영상진단장비','ICT','H-402','메디라인'),
    ('기타의료기기','Ultrasound','CWM-302','청우메디칼'),
    ('수술실/병원가구','O2 Tank Cart','','지엠텍'),
    ('기타의료기기','전동체어','','엠코니'),
    ('병상/침대류','전동테이블','E202','hck'),
    ('검사/측정장비','체성분분석기','ACCUNIQ, BC300','셀바스코리아'),
    ('물리치료/재활장비','저주파자극기','EST-1000','서진메디텍'),
    ('기타의료기기','Auto Tourniquet','','퍼슨메디칼'),
    ('기타의료기기','Tread Mill','5080','네오텍'),
    ('멸균/소독장비','U-V Sterilizer','KRS-700T-62L','카리스'),
    ('기타의료기기','환자베개 카바','캥거루식','금성까운'),
    ('물리치료/재활장비','근이완자극기','01M4','영일엠'),
    ('수술실/병원가구','Sheet Cover','면-누빔','금성까운'),
    ('기타의료기기','Stall Bar','W400','네오텍'),
    ('수술실/병원가구','Mobile Utility Cart','Y201A','열린세상'),
    ('물리치료/재활장비','ESWT','Airgun','굿플'),
    ('수술장비','고주파수술기','RF-180','아이티시'),
    ('수술장비','Operating Light','KN-LED48','케이엔티'),
    ('기타의료기기','Cast Cutter','HCC-114','한신메디칼'),
    ('기타의료기기','Auto Tens','GS-3070','굿플'),
    ('환자모니터링장비','Defibrillator','','메디아나'),
    ('병상/침대류','전동테이블','컨트롤박스','hck'),
    ('기타의료기기','Vaginal Speculum','','장우양행'),
    ('기타의료기기','Laryngoscope','3 Blade','파사우'),
    ('병상/침대류','전동테이블','PAMB-730','팜파스'),
    ('병상/침대류','전동테이블','M2-6','영일엠'),
    ('기타의료기기','휠체어체중계','GWS-200','지테크인터내셔널'),
    ('기타의료기기','Ion Cooler','','오릭스'),
    ('물리치료/재활장비','CPM','FLEXIEE1','케어테크'),
    ('병상/침대류','Examining Table','MB-2100','대상의료기'),
    ('내시경장비','내시경 Scope Cabinet','SKHP-7706NM','선경산업'),
    ('병상/침대류','Examining Table','KF-908A','엠코니'),
    ('기타의료기기','천정레일형보행훈련기','','네오텍'),
    ('영상진단장비','X-Ray','REX-525R','리스템'),
    ('기타의료기기','Operating Microscope','','칼자이스'),
    ('수술장비','Operating Light','','케이엔티'),
    ('기타의료기기','Auto Tens','GP-500P','굿플'),
    ('병상/침대류','전동테이블','M2-8','영일엠'),
    ('병상/침대류','Stretcher Car','S3-1,전동1단','영일엠'),
    ('기타의료기기','ENT-Chair','','제이알메디'),
    ('환자모니터링장비','Pulse Oxymeter','Bionet,OXY9Wave','비스토스'),
    ('영상진단장비','Lipo Suction','JS-008','진솔의료기'),
    ('영상진단장비','Suction Unit','','진솔의료기'),
    ('환자모니터링장비','자동혈압계','BPbio750','인바디'),
    ('병상/침대류','전동테이블','CTT-200','펄시'),
    ('병상/침대류','Stretcher Car','SKB-201-1','삼기메디칼'),
    ('기타의료기기','Corner Stair','W700','아성'),
    ('병상/침대류','Examining Table','','장미'),
    ('온열/냉각기기','Hot-Pack Unit','GP-12PN','굿플'),
    ('영상진단장비','X-Ray Thyroid Collar','갑상선보호대','성광메디텍'),
    ('기타의료기기','Cell Counter','','마인드레이'),
    ('기타의료기기','Photo Therapy Unit','','비올'),
    ('기타의료기기','납안경','SK-90','성광메디텍'),
    ('병상/침대류','Patient Stool','AS-300','엠코니'),
    ('수술장비','수술준비대','','지엠텍'),
    ('환자모니터링장비','EKG','MeCA406i','제로원'),
    ('기타의료기기','MR-Kit','','대합성'),
    ('기타의료기기','Allis Tissue Forcep','5x6t','장우양행'),
    ('기타의료기기','Syringe Pump','SP8800',''),
    ('환자모니터링장비','Patient Monitor','M40','메디아나'),
    ('기타의료기기','Bobath Table','R2-A','네오텍'),
    ('기타의료기기','Classic Ladder Barrel','CLB 500',''),
    ('기타의료기기','Thermometer','귓속형체온계','비스토스'),
    ('병상/침대류','Stretcher Car','MB-3000','hck'),
    ('온열/냉각기기','Hot-Pack Unit','KRS-12PA','카리스'),
    ('온열/냉각기기','Hot-Pack Unit','','아성'),
    ('수술실/병원가구','Mobile Utility Cart','Y201C','열린세상'),
    ('기타의료기기','Dependent Bed','YB-A1003','영남베드'),
    ('환자모니터링장비','디지탈혈압계','','오므론'),
    ('기타의료기기','Urine Strip','10종, 100s/pack','디에프아이'),
    ('병상/침대류','Stretcher Car','YB-E1003','영남베드'),
    ('환자모니터링장비','메타식혈압계 스텐드','CK-142','인바디'),
    ('병상/침대류','Examining Table','KS-105','엠코니'),
    ('물리치료/재활장비','근이완자극기','TURBO-SASO','사소'),
    ('기타의료기기','Work Table 보조테이블','W800','네오텍'),
    ('검사/측정장비','Urine Analyzer','Urometer-720','디에프아이'),
    ('병상/침대류','Stretcher Car','DSM101B','대상의료기'),
    ('기타의료기기','Auto Tens','PMT-175','굿플'),
    ('멸균/소독장비','Plazma Sterilizer','','메디스터'),
    ('기타의료기기','Dependent Bed','','영암베드'),
    ('기타의료기기','Foot Step','2단발판-Steel','지엠텍'),
    ('기타의료기기','Wheel Chair','침대형','메디타운'),
    ('영상진단장비','C-Arm','방호판','디알뷰'),
    ('물리치료/재활장비','근이완자극기','','영인바이오텍'),
    ('기타의료기기','Centrifuge','DM0506','나스코코리아'),
    ('영상진단장비','X-Ray Apron','0.3mm/pb','성광메디텍'),
    ('온열/냉각기기','Hot-Pack Unit','24Pack','아성'),
    ('멸균/소독장비','Plazma Sterilizer','MDU-80V','메디스터'),
    ('수술실/병원가구','Mobile Utility Cart','YDS302','열린세상'),
    ('수술실/병원가구','IV Pole','링겔대 3발바퀴형','지엠텍'),
    ('기타의료기기','Instruments','','파사우'),
    ('기타의료기기','Uterine Biopsy Punch','','솔고의료기'),
    ('병상/침대류','Tilting Table','R3','영일엠'),
    ('물리치료/재활장비','ESWT','Airgun Handpiece','굿플'),
    ('기타의료기기','Fixed Table 바퀴형','TS-100','대경공업'),
    ('수술실/병원가구','Emergency Cart','','지엠텍'),
    ('영상진단장비','C-Arm','핸드스위치','잼스헬스케어'),
    ('기타의료기기','Compartmented Tray','','지엠택'),
    ('기타의료기기','환자베개 카바','레자','칠성'),
    ('영상진단장비','Suction Unit','MS-20','엠테크놀로지'),
    ('기타의료기기','환자베개속','','칠성'),
    ('병상/침대류','Patient Stool','AS-305','엠코니'),
    ('기타의료기기','Head Light','KS-03','새하늘바이오텍'),
    ('영상진단장비','Dressing Jar','스폰지캔,2호','지엠텍'),
    ('수술장비','Operating Table','오물통','진솔의료기'),
    ('수술기구/소모품','Mosquito Forceps','CVD,12cm','파사우'),
    ('기타의료기기','Side Lamp halogen','JS-013','진솔의료기'),
    ('환자모니터링장비','자동혈압계','HBP-9020','오므론'),
    ('수술실/병원가구','배식카트  (20인용)','라온카트','엔에스제이'),
    ('수술장비','수술준비대','1200x500x900mm','지엠텍'),
    ('온열/냉각기기','온장고','KRS-203A','카리스'),
    ('병상/침대류','전동테이블','M3-2','영일엠'),
    ('영상진단장비','Smoke Suction','DS-2000E','대신엔터프라이즈'),
    ('환자모니터링장비','자동혈압계','BP868F','AMP'),
    ('기타의료기기','Cervical Biopsy Punch','23cm','장우양행'),
    ('치료장비','Infrared Lamp','','해동메디칼'),
    ('영상진단장비','Suction Unit','JS-30','진솔의료기'),
    ('검사/측정장비','당화혈색소','Clover A1c / HbA1C','그린바이오텍'),
    ('기타의료기기','세탁물운반카','','지엠텍'),
    ('영상진단장비','ICT','케이블','굿플'),
    ('기타의료기기','전침','STN-111','스트라텍'),
    ('기타의료기기','Wheel Chair','거상병원형','메디라인'),
    ('기타의료기기','Parallel Bars','W600','아성'),
    ('영상진단장비','Dressing Forceps','14cm','파사우'),
    ('기타의료기기','Placenta Forcep','','파사우'),
    ('병상/침대류','전동테이블','사이즈변경','네오텍'),
    ('멸균/소독장비','Steam Sterilizer','','홍익'),
    ('영상진단장비','X-Ray Apron','0.5mm/pb','성광메디텍'),
    ('병상/침대류','Patient Stool','AS-302','엠코니'),
    ('기타의료기기','O2 Tank','20kg','신영특수'),
    ('수술실/병원가구','Mobile Utility Cart','Y101B','열린세상'),
    ('기타의료기기','사각베개','','웰리스코리아'),
    ('온열/냉각기기','온장고','KRS-204','카리스'),
    ('수술장비','고주파수술기','고주파팁','아이티시'),
    ('기타의료기기','TDP','CQ-31,스텐드타입','대원'),
    ('멸균/소독장비','U-V Sterilizer','KRS-650T-40L','카리스'),
    ('수술실/병원가구','IV Pole','5발-바퀴유:손잡이','지엠텍'),
    ('기타의료기기','Biological Indicator Incubator','배양기','대한랩테크'),
    ('기타의료기기','Biopsy Punch Forcep','25cm','가디언'),
    ('물리치료/재활장비','근이완자극기','SASO','영일엠'),
    ('온열/냉각기기','온장고','KRS-202D','카리스'),
    ('기타의료기기','Glucometer Strip','100s/box','올메디쿠스'),
    ('기타의료기기','Dependent Bed','YB-A1001','영남베드'),
    ('병상/침대류','전동테이블','Siderail','엠케이베드'),
    ('온열/냉각기기','Hot-Pack Unit','GP-12PD','굿플'),
    ('기타의료기기','전침','STN-330','스트라텍'),
    ('병상/침대류','Examining Table','YB-E2001','영남베드'),
    ('영상진단장비','Portable Suction','JS-20','진솔의료기'),
    ('영상진단장비','Dressing Car','조립,대','지엠텍'),
    ('기타의료기기','타임호출기','GP-900M','도도텍'),
    ('기타의료기기','두타베드','','카스피'),
    ('물리치료/재활장비','근이완자극기','SR-2003','영인바이오텍'),
    ('물리치료/재활장비','근이완자극기','01M3','영일엠'),
    ('병상/침대류','Stretcher Car','KHS-131','영남베드'),
]

# ── 4. 중복 제거 및 등록 ─────────────────────────────────────────
print('\n=== 장비 등록 ===')
skip_db = 0
skip_batch = 0
inserted = 0
batch_models = set()  # 이번 배치에서 이미 처리한 모델명

to_insert = []
for cat_name, item_name, model_name, manufacturer in RAW:
    model_key = model_name.lower().strip()

    # DB 중복 체크 (모델명 있는 경우만)
    if model_key and model_key in existing_models:
        skip_db += 1
        continue

    # 배치 내 중복 체크 (모델명 있는 경우만)
    if model_key and model_key in batch_models:
        skip_batch += 1
        continue

    cat_id = CAT_ID_MAP.get(cat_name, '기타의료기기')

    to_insert.append({
        'cat_id': cat_id,
        'cat_name': cat_name,
        'category': cat_name,
        'item_name': item_name,
        'model_name': model_name,
        'manufacturer': manufacturer,
        'price': None,
        'model_notes': '',
        'alt_text': '',
        'description': '',
        'specs': [],
        'origin': '',
        'cert': '',
        'as_period': '',
        'warranty': '',
    })

    if model_key:
        batch_models.add(model_key)

print(f'  DB 중복 스킵: {skip_db}개')
print(f'  배치 내 중복 스킵: {skip_batch}개')
print(f'  등록 예정: {len(to_insert)}개')

# 50개씩 배치 insert
BATCH = 50
for i in range(0, len(to_insert), BATCH):
    chunk = to_insert[i:i+BATCH]
    result = supabase_post('equipment', chunk, prefer='resolution=ignore-duplicates')
    if result is not None:
        inserted += len(chunk)
        print(f'  [{i+len(chunk)}/{len(to_insert)}] 등록 완료')
    else:
        print(f'  [{i+len(chunk)}/{len(to_insert)}] 오류 발생')

print(f'\n=== 완료: {inserted}개 등록, {skip_db}개 DB중복, {skip_batch}개 배치중복 ===')
